services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: jobberpassword
      POSTGRES_DB: jobber
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
